version: '3.3'
services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: 'spring'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'